# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e23cd655c0be99efdf66c1eeab210f6a8fbb1065783f540ef8bfd207f0d3d5a3b778b7365aa9c9a24894f88a4d408c9c7298adecb203018b844fd03a90fed3af

test:
  secret_key_base: 0a290baa2fc3a97d8916eee662ff20e69f5aa3e168e814eab3b23dbb36e5e80452b80fec08526185a4ab31d7bfd67794f73f068cd3053a41498cbd4cf7be6dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
